version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout

      - run: |
          set -o pipefail &&
          xcodebuild
            CODE_SIGNING_REQUIRED=NO
            CODE_SIGN_IDENTITY=
            PROVISIONING_PROFILE=
              -sdk iphonesimulator
              -destination 'platform=iOS Simulator,OS=11.1,name=iPhone 7'
              -workspace DrawerKit.xcworkspace
              -scheme "DrawerKitDemo"
          clean build test

      - run: pod lib lint
      - run: carthage build --no-skip-current --cache-builds
